---
title: "FFAQR Vignette"
author: "Gomez and Nemenov"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Merging Fama/French and AQR Data}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

This is a package that merges AQR's Quality Minus Junk data set with Fama and French's (FF) portfolio data based on five factors: market returns (less the risk free rate), small minus big, high (book to market) minus low, investment, and operating profitability. The purpose of this package is to clean the data and recommend to the user interesting follow up questions and opportunities for further research.

This package was developed to facilitate further use of the AQR and FF data sets for Econ 20: Quantitative Data Analysis during winter study at Williams College. We would like to thank David Kane and our classmates for their help and guidance.

## Package Use

The package can be initiated in two ways. The cleanAll() function will clean the data sets already included with the package and will subsequently present the results in the global environment. Alternatively, for those who want updated information, updateData() will pull the newest version of the data from AQR's and Kenneth French's respective websites and clean it.

Please note that this package will create and manipulate directories within the project directory. It will add and update data in a folder aptly named "data", and may create a new folder named "cleanData".

## Useful Functions

updataData() - Updates and cleans all data, exporting to global environment.
updateData(clean=FALSE) - Only updates data.
cleanAll() - Cleans all data, exporting to global environment.

## Data Sources

FFCMA - Portfolios sorted by investment, monthly.

FFHMLDaily - Portfolios sorted by book to market value, daily.

FFHMLMonthly - Portfolios sorted by book to market value, monthly, includes number of firms and average size of firms included in portfolios.

FFRMW - Portfolios sorted by operating profitability, monthly.

FFSMBDaily - Portfolios sorted by size, daily.

FFSMBMonthly - Portfolios sorted by size, monthly, includes number of firms and average size of firms included in portfolios.

QMJ10QMonthly - 10 portfolios of US and Global equities (each) sorted by AQR's measure of quality minus junk, monthly.

QMJMonthly -AQR's monthly returns on the quality minus junk factor, includes AQR's returns on portfolios selected through several additional criteria discussed below.

## Detailed Explanation of Data

Note: The following FF datasets are split into separate subsets that group observations by terciles, quintiles and deciles.

FFCMA

Datasets beginning with FFCMA contain portfolios constructed with respect to investment, which is defined as the change in total assets from the fiscal year ending in year t-2 to the fiscal year ending in t-1, divided by t-1 total assets. It contains value and equal weighted returns for portfolios formed on investment. 

FFHML 

Datasets beginning with FFHML contain portfolios constructed with respect to ratio of book equity to market equity (BE/ME), which is defined as  book equity at the last fiscal year end of the prior calendar year divided by ME at the end of December of the prior year. It contains value and equal weighted returns for portfolios formed on BE/ME. Those datasets that continue as FFHMLDaily contain portfolios that are constructed with daily information, while those that continue as FFHMLMonthly contain portfolios that are constructed with monthly information. Data describing the number of firms and the average size of firms is included for FFHMLMonthly. 

FFRMW

Datasets beginning with FFRMW are constructed with respect to operating profitability, which is defined as operating profits ( sales minus cost of goods sold, minus selling, general, and administrative expenses, minus interests expense) divided by book equity at the last fiscal year end of the prior calendar year. Among these datasets included are those that contain value and equal weighted returns for portfolios. 

FFSMB

Datasets beginning with FFSMB are constructed with respect to the size. SMB or small minus big accounts for the spread between small and large sized firms, which is based on the company’s market capitalization. Among the datasets include are those that contain value and equal weighted returns for portfolios. Additionally, returns by this metric are available as monthly or daily data.  Data describing the number of firms and the average size of firms is included for FFSMBMonthly. 

The following AQR datasets provide AQR's data for returns on several FF factors (including size and book to market), momentum, and the relevant risk free rate.

QMJ10QMonthly

Dataset contains monthly returns, in excess of t-bills, of 10 value-weighed, long-only portfolios sorted on quality.  A quality security is defined as one that, all else equal, investors are willing to pay a higher price for: stocks that are safe, well-managed, profitable and growing. It includes 10 quality sorted portfolios, for both a long sample of U.S equities and a broad sample of global equities. It also includes the spread between highest quality portfolio and the lowest quality portfolio. 

QMJMonthly

Dataset contains monthly self-financing excess returns of long/short Quality Minus Junk (QMJ) factors. QMJ is our quality-minus-junk factor that goes long high quality stocks and short low quality stocks. A quality security is defined as one that, all else equal, investors are willing to pay a higher price for: stocks that are safe, well-managed, profitable and growing. QMJ factors are constructed for U.S equities, 23 international equity markets, and multiple aggregates.

## Troubleshooting Common Errors

Unable to set working directory?
Some functions make use of moving into subdirectories before moving back out into the working directory, please make sure that the project folder is set as the folder directory before attempting to clean or download data.

Unable to import AQR data?
If you cannot run read.xlsx() on the daily AQR data, you need to allocate more memory to your Java heap (see Java's Xmx setting).
